2021-3-23 frontend and backend nev set
FDUCSLG/fducslg pull request #9
Opened 2021-03-23 11:58 UTC by Entropy0491

关于 配置前后端心得分享的文件pr

2021-03-24 00:02 UTC, ichn-hu requested changes

2021-03-24 00:02 UTC, ichn-hu commented on content/blog/2021-3-23-windows-fdxk-config.md
> +# 〇、本文阅读不完全指北
请修改标题为： fdxk.info 后端开发在 win10 上的配置

2021-03-24 00:02 UTC, ichn-hu commented on content/blog/2021-3-23-windows-fdxk-config.md
> +本文档由刘煜、李睿潇两名同学编写，基于两人在Windows系统下安装环境时的个人经历制作。
本文是面向 CSLG 和外部发表的，还应该简单介绍一下背景。

2021-03-24 00:02 UTC, ichn-hu commented on content/blog/2021-3-23-windows-fdxk-config.md
> +本文档由刘煜、李睿潇两名同学编写，基于两人在Windows系统下安装环境时的个人经历制作。
另外，请在所有中英文混合排版的地方，在中英文之间添加空格，如

`基于两人在 Windows 系统下` 而不是

`基于两人在Windows系统下`

2021-03-24 00:02 UTC, ichn-hu commented on content/blog/2021-3-23-windows-fdxk-config.md
> +#### 1）简易安装：
请修改标题的层级，这里应该不必要采用标题的形式，而是列表给出即可

2021-03-24 00:02 UTC, ichn-hu commented on content/blog/2021-3-23-windows-fdxk-config.md
> + “Windows + R”键开启“运行”，输入“winver”，查看您的Windows版本，这将是检查您的系统能否使用WSL（Windows Subsystem for Linux）功能的重要依据。
对于按键或小代码块，应该使用 `Windows + R` 的等宽代码块展示。使用 Esc 下的 backtick 符号框住即可。

2021-03-24 00:02 UTC, ichn-hu commented on content/blog/2021-3-23-windows-fdxk-config.md
> +## 1.   检查Windows版本：
请控制标题前的空格数量，并保持标题的一致性（标题不需要编号，也不需要特别多的层级）

2021-03-24 00:03 UTC, ichn-hu commented
https://github.com/FDUCSLG/fducslg/blob/25f6af924be3daf82e1ddb06e2b48512ff2f5719/content/blog/2021-3-23-windows-fdxk-config.md

可以通过这个链接预览内容

2021-03-29 04:39 UTC, Entropy0491 commented
按照要求修改了文章，提交了新的内容！但是使用的还不太熟练，忘了在第二次提交 pr 时候加上详细内容了，抱歉orz。
修改过程难免出现纰漏，也麻烦胡助辅多多费心！: )
改动有：
·加入了关于 CSLG 和本文写作的一些经历
·修改了字母和汉字之间的链接，加入了空格
·取消了内容前边的编号，采用标题层级分隔
·修复了一些不太通顺的句子，删除了一些无用的代码块
·用等宽代码块取代了一些大代码块

2021-03-30 01:26 UTC, ichn-hu approved these changes
LGTM，两位干得漂亮！

2021-03-30 01:26 UTC, ichn-hu commented on content/blog/2021-3-28-windows-fdxk-config.md
> +```
可以用 admonitions，见：https://squidfunk.github.io/mkdocs-material/reference/admonitions/

我直接帮你改了

2021-03-30 01:27 UTC, merged